version: "3"

services:
  db:
    build: .docker/postgres
    container_name: wish-list-db
    ports:
      - 5432:5432
    volumes: 
      - .docker/postgres/db:/var/lib/postgresql/data:z
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=docker

  app:
    build: .
    command: npm run start:dev
    container_name: wish-list-node
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
   

    
  
